### ISSUE TITLE
IMPORTANT NOTICE: [python-buildpack] End of Support for Python versions 3.5.x after 2020-10-14

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/python-runtime#88]
The first release of the Python buildpack after 2020-10-14 will no longer include Python versions 3.5.x. These Python versions will no longer be supported upstream[1]. Please migrate your Python apps to supported versions of Python before that time.

Note: If you’d like to use a different Python version, please configure your application to select that version.

[1] - https://www.python.org/dev/peps/pep-0478/

**Comment by ryanmoran** [comment]
Python 3.5 was removed in https://github.com/paketo-community/python-runtime/commit/ad493ccedc7fdd13187ab187354168e08e7a6c8b#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3. Does that mean we can close this?
